package com.gmail.calorious.cyclistdirections.general;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

public class User {
    /*
     * General class for User
     * Each phone should be identified from MAC Address, Settings.Secure#ANDROID_ID, and a random unique identifier generated by the application.
     */
    private String uniqueId;
    private String macAddress;
    private String androidId;

    public User(long uniqueIdentifier) {
        // Obtain other data and update accordingly
    }

    // Create new one
    protected User(String uniqueId, String macAddress, String androidId) {
        this.uniqueId = uniqueId;
        this.macAddress = macAddress;
        this.androidId = androidId;
    }

    public String getUniqueIdentifier() {
        return uniqueId;
    }

    public String getMacAddress() {
        return macAddress;
    }

    protected String getAndroidId() {
        return androidId;
    }

    public String getEncodedAndroidId() {
        byte[] bytes = androidId.getBytes(StandardCharsets.UTF_8);
        return Base64.getEncoder().encodeToString(bytes);
    }
}
