package com.gmail.calorious.cyclistdirections.general;

public class User {
    /*
     * General class for User
     * Each phone should be identified from MAC Address, Settings.Secure#ANDROID_ID, and a random unique identifier generated by the application.
     */

}
